'use strict';
/* Edit this file to refresh the fictional market stories. */
const PMM_NEWS_DATA={
 disclaimer:'Simulation News: The companies and events in these reports are fictional and created for this game.',
 bonds:{label:'Government Bonds',risk:'Low',stories:{
  positive:{headline:'New School Building Plan Lifts Bond Demand',preview:'A large school building plan needs long-term funding. More families are now looking at government bonds.',paragraphs:['The state has approved a plan to build twelve new schools. The work will include classrooms, libraries and sports areas.','The project will be paid for over many years. This has brought more attention to government bonds, which are often used to support large public projects.','Several family investment groups said they may buy more bonds because the payments are planned and steady. This new demand could support bond values.','However, bonds usually grow slowly. If other investments offer much higher returns, some investors may move their money away again.'],think:'Would a slow and steady choice suit your money plan?'},
  stable:{headline:'Bond Market Waits for the Next Budget Update',preview:'Government bonds are moving by very small amounts while investors wait for new spending plans.',paragraphs:['Government leaders have not announced any major new projects this week. Most current road, hospital and school projects are continuing as planned.','Bond investors are waiting for the next budget update before making large decisions. There is no strong reason to buy or sell right now.','Small changes may still happen each day, but the market is likely to remain calm until new information arrives.'],think:'Would you wait for more news, or choose a steady investment now?'},
  negative:{headline:'Investors Move Money Towards Faster-Growing Companies',preview:'Some investors are selling bonds to try investments with higher possible returns.',paragraphs:['Several technology and energy companies have reported strong sales. This has encouraged some investors to move money away from government bonds.','Bonds are still seen as a steadier choice, but their returns may look less exciting when company shares are growing quickly.','If more investors sell bonds, bond values may face a small fall. However, unexpected bad news in the share market could bring investors back to safer choices.'],think:'Is a higher possible reward worth taking more risk?'}}},
 fund:{label:'Diversified Fund',risk:'Medium',stories:{
  positive:{headline:'Strong Results Arrive from Several Industries',preview:'Technology, food and clean-energy companies have all reported better sales this month.',paragraphs:['BrightBot AI sold more school robots than expected, while WonderSnack Foods opened stores in three new cities. SunSpark Energy also signed a large battery agreement.','A diversified fund holds small parts of many different businesses. Good results across several industries can support the whole fund.','Fund managers said they are pleased that growth is not coming from only one company. This can reduce the damage if one business later has a problem.','Costs are still rising for transport and materials, so the positive results are not guaranteed to continue.'],think:'Why might many different companies be safer than only one company?'},
  stable:{headline:'Good News and Bad News Balance the Mixed Fund',preview:'Some companies in the fund grew, but others faced higher costs and slower sales.',paragraphs:['PixelForge Games reported strong downloads for a new game. At the same time, FreshFizz Drinks paid more for bottles and transport.','The diversified fund owns parts of both growing and struggling companies. The gains and losses have mostly balanced each other.','Investors are watching the next set of company reports before making a bigger decision. The fund may continue to move in a small range.'],think:'Can one strong company lift a whole mixed fund?'},
  negative:{headline:'Slower Sales Spread Across Shops and Factories',preview:'Several businesses in the mixed fund have received fewer orders, while costs remain high.',paragraphs:['WonderSnack Foods sold fewer products after raising prices. A large factory owned by SwiftStep Shoes also reduced its weekly production.','Because the fund includes many businesses, problems in several industries can affect its total value. Investors have started to become more careful.','Some technology companies remain strong, which may soften the fall. Even so, the overall news is weaker than last month.'],think:'Would you invest now, or wait for the next company reports?'}}},
 property:{label:'Property Fund',risk:'Medium',stories:{
  positive:{headline:'BrightCity Wins Approval for a New Town Centre',preview:'A large housing and shopping project has received approval, and early buyer interest is strong.',paragraphs:['BrightCity Property can now begin work on 600 homes, a supermarket and a community centre. The company says construction will start next month.','More than 200 families have already asked for information about the homes. Several shops also want space in the new centre.','Strong early interest may help property companies earn more money and could support property fund values.','Building materials and worker costs remain high. Delays or cost increases could reduce the final profit.'],think:'Which matters more: strong buyer interest or high building costs?'},
  stable:{headline:'Home Sales Remain Steady as Buyers Wait',preview:'Homes are still selling, but buyers are taking more time before making decisions.',paragraphs:['Riverstone Developments sold about the same number of homes as last month. Rental demand also stayed steady.','Buyers are comparing prices carefully and many have not rushed to sign contracts. Builders are continuing current projects but have announced few new ones.','Without a major change in sales or costs, property fund values may move only a little.'],think:'What new event could change this quiet property market?'},
  negative:{headline:'Riverstone Stops Work After Building Problems',preview:'Engineers found serious cracks at a large building site, and construction has stopped for safety checks.',paragraphs:['Riverstone Developments stopped work on two apartment buildings after engineers found cracks in part of the foundation. No residents were living at the site.','The company must now pay for more tests and may need to rebuild some sections. Buyers who planned to move in this year have been told there could be a delay.','Investors are concerned that the repairs will cost a large amount of money. Other property companies are also checking similar projects.','If the problem is fixed quickly, the damage may be limited. A long delay could place more pressure on the property fund.'],think:'How could one building problem affect other property companies?'}}},
 shares:{label:'Share Market',risk:'High',stories:{
  positive:{headline:'BrightBot AI Receives a Huge School Robot Order',preview:'BrightBot AI has received its largest order ever, but the company must expand quickly to deliver it.',paragraphs:['BrightBot AI makes learning robots that help children practise spelling, maths and coding. A group of schools has now ordered 5,000 of the newest model.','The order is much larger than the company expected. BrightBot plans to hire more workers and open a second factory to build the robots.','Some investors believe the order could bring strong sales and future growth. Interest in technology shares increased after the announcement.','Opening a factory will cost a lot of money. If robots arrive late or develop technical problems, schools may cancel part of the order.'],think:'Would you invest now, or wait to see whether delivery starts on time?'},
  stable:{headline:'Share Investors Wait for Company Results',preview:'Several companies are preparing reports, but no major results have been released yet.',paragraphs:['BrightBot AI, PixelForge Games and SunSpark Energy will report their latest sales soon. Investors want to know whether recent products are selling well.','Some traders bought small amounts of shares, while others sold and waited. These actions have mostly balanced each other.','Prices may move up and down by small amounts until the company reports provide clearer information.'],think:'Is waiting sometimes a useful investment decision?'},
  negative:{headline:'BrightBot Stops Robot Sales After a Safety Fault',preview:'A battery fault has stopped sales of BrightBot AI’s newest robot while engineers investigate.',paragraphs:['A school reported that one learning robot became unusually hot while charging. BrightBot AI has asked customers to stop using that model until safety checks are complete.','The company paused new sales and may need to replace batteries in thousands of robots. No serious injuries were reported in this fictional story.','Investors are worried about repair costs and damage to the company’s name. Some technology shares fell after the announcement.','BrightBot says engineers are close to finding the cause. A quick and successful repair could rebuild customer trust, but a long delay may create larger losses.'],think:'Would a fast repair change your investment decision?'}}}
};
