'use strict';
const PMM_NEWS_DATA={
 disclaimer:'Simulation News: The companies and events in these reports are fictional and created for this game.',
 tips:['Do not put all your money in one investment.','A higher possible reward usually means a higher risk.','One good day does not promise future growth.','Think about how much money you are ready to lose.'],
 bonds:{label:'Government Bonds',risk:'Low',stories:{positive:[['New School Plan Helps Bond Demand','A new school building plan needs long-term funding. More families are choosing government bonds.']],stable:[['Bond Market Stays Calm','Government bonds are moving by very small amounts. There is no strong direction today.']],negative:[['Investors Look for Higher Returns','Some investors have moved money away from bonds. Bond demand may fall slightly.']]}},
 fund:{label:'Diversified Fund',risk:'Medium',stories:{positive:[['Several Markets Show Steady Growth','Shops, technology companies and energy businesses have reported better results. The mixed fund may grow.']],stable:[['Mixed Fund Has a Quiet Week','Some parts of the fund rose while others fell. The total value is changing only a little.']],negative:[['Several Businesses Face Slower Sales','Shops and factories have reported fewer orders. The diversified fund may face a weak period.']]}},
 property:{label:'Property Fund',risk:'Medium',stories:{positive:[['BrightCity Wins a Major Building Plan','BrightCity Property has received approval for new homes and shops. Many buyers have shown interest.']],stable:[['Property Prices Move Slowly','Home sales are steady and building activity is calm. Property values may change only a little.']],negative:[['Riverstone Stops a Building Project','Riverstone Developments found problems at a building site. Work has stopped while the company checks the project.']]}},
 shares:{label:'Share Market',risk:'High',stories:{positive:[['BrightBot AI Launches a Learning Robot','BrightBot AI has created a new learning robot. Many schools have placed early orders.'],['SunSpark Builds a Better Battery','SunSpark Energy has tested a battery that lasts longer. Investors are watching the company.']],stable:[['Share Market Waits for New Results','Companies have shared very little new information. Share prices are moving by small amounts.']],negative:[['BrightBot Finds a Robot Safety Problem','BrightBot AI has found a problem in a new robot. Sales have stopped while the company checks the product.'],['CloudQuest Reports Weaker Sales','CloudQuest Interactive sold fewer games this month. Some share prices may come under pressure.']]}}
};
